from agent.settings import config
from tqdm.auto import tqdm
import time
from datasets import load_dataset
from pinecone import Pinecone, ServerlessSpec
from semantic_router.encoders import OpenAIEncoder

class PineconeOperations:

    def __init__(self):
        self.api_key = config["pinecone_api_key"]

    def pinecone_index(self, index_name: str):
        pc = Pinecone(api_key=self.api_key)
        spec = ServerlessSpec(cloud="aws", region="us-east-1")
        if index_name not in pc.list_indexes().names():
            pc.create_index(
                index_name,
                dimension=1536, # the length of the vector generated by the encoder above.
                metric='dotproduct',
                spec=spec
            )
            # wait for index to be initiated
            while not pc.describe_index(index_name).status["ready"]:
                time.sleep(1)

        index = pc.Index(index_name)
        time.sleep(1)
        index.describe_index_stats()
        return index

    def dataset_load(self):
        dataset = load_dataset("jamescalam/ai-arxiv2-semantic-chunks", split="train")
        return dataset

    def pinecone_load(self):
        index = self.pinecone_index("gpt-4o-research-agent")
        dataset = self.dataset_load()
        data = dataset.to_pandas().iloc[:10]
        batch_size = 128
        encoder = OpenAIEncoder(name="text-embedding-3-small")
        for i in tqdm(range(0, len(data), batch_size)):
            i_end = min(len(data), i+batch_size)
            batch = data[i:i_end].to_dict(orient="records")
            #get batch data
            metadata = [{
                "title": r["title"],
                "content": r["content"],
                "arxiv_id": r["arxiv_id"],
                "references": list(r["references"])
            } for r in batch]
            ids = [r["id"] for r in batch]
            content = [r["content"] for r in batch]
            embeds = encoder(content)
            index.upsert(vectors=zip(ids, embeds, metadata))
        return index
